config/routes.rb
DesignWithMe::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :companies do
    collection { post :import }
  end
  root :to => "sessions#new"
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :address, :comments, :contact, :industry,
                  :minimum_order, :name, :phone, :ranking,
                  :subindustry, :website, :id

  def self.to_csv(companies)

    fields = [:name, :contact]

    CSV.generate do |csv|
      csv << [:id, :name, :contact, :address, :phone, :website, :industry, :subindustry, :minimum_order, :comments]
      companies.each do |company|
        csv << [company.id, company.name, company.contact, company.address, company.phone, company.website, company.industry, company.subindustry, company.minimum_order, company.comments]
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Company.create! row.to_hash
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation, :admin, :member,
                  :cell_phone, :first_name, :last_name, :home_phone, :industry,
                  :website

  validates_uniqueness_of :email
  validates_presence_of :email, :first_name, :last_name

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_url, alert: 'Not Authorized' if current_user.nil?
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_filter :authorize

  # GET /companies
  # GET /companies.json
  def index

    @companies = Company.order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.csv { send_data Company.to_csv(@companies) }
      format.json { render json: @companies }

    end
  end

  def import
    Company.import(params[:file])
    redirect_to companies_path, notice: "Companies imported."

  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
  def sort_column
    params[:sort] || "name"
  end

  def sort_direction
    params[:direction] || "asc"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to companies_path, notice: "Logged In!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize, :only => [:index, :show]

  def new
    @user = User.new
  end

  def create
    puts "User params : ", params[:user]

    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def show

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes!(params[:user])
    redirect_to users_path
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  #before_filter :authorize, only: [:edit, :update]
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>

  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :industry %><br />
    <%= f.text_field :industry %>
  </div>

  <div class="field">
    <%= f.label :subindustry %><br />
    <%= f.text_field :subindustry %>
  </div>

  <div class="field">
    <%= f.label :ranking %><br />
    <%= f.text_field :ranking %>
  </div>

  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_field :comments %>
  </div>

  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :minimum_order %><br/>
    <%= f.text_field :minimum_order %>
  </div>

  <div class="actions">
    <%= f.submit 'Create Company', class: 'button' %>
    <%= link_to 'Cancel', companies_path, class: 'button' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<%= link_to 'New Company', new_company_path, class: 'button' %>
<br/>
<br/>
<p>
  Download:
  <%= link_to "CSV", companies_path(format: "csv") %>
</p>
<div class="row">
  <div class="large-8 columns">
    <table id="companies">
      <thead>
          <tr>
            <th><%= sortable "Name" %></th>
            <th><%= sortable "Contact" %></th>
            <th><%= sortable "Website" %></th>
            <th><%= sortable "Industry" %></th>
            <th><%= sortable "minimum_order", "Minimum Order" %></th>
            <th>Actions</th>
          </tr>
      </thead>
      <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%=link_to company.name, edit_company_path(company) %></td>
        <td><%= company.contact %></td>
        <td><%= company.website %></td>
        <td><%= company.industry %></td>
        <td><%= company.minimum_order %></td>
        <td>
          <%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
    </table>
  </div>
</div>

<br />

<h2>Import Companies</h2>
<p>
  Alternatively, you can import companies by selecting a file and uploading it.
</p>
<%= form_tag import_companies_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
<% end %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/home/index.html.erb
<%= render 'sessions/new' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Designwithme", root_path, :class => 'brand' %>
<% if current_user %>
    Logged in as <%= current_user.email %>
    <%= link_to "Log Out", logout_path %>
<% else %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <nav class="top-bar">
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h1><a href="#">Design With Me</a></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <li class="divider"></li>
        <li class="active"><%= link_to "Companies", companies_path %></li>
        <li><a href="#"><%= link_to "Designers", users_path %></a></li>
        <li class="divider"></li>
      </ul>

      <!-- Right Nav Section -->
      <ul class="right">
        <% if current_user.nil? %>
            <li><%= link_to "Log In", login_path %></li>
        <% else %>
            <li><%= link_to "Welcome Back (logout)", logout_path %></li>
        <% end %>
      </ul>
    </section>
  </nav>
    <div class="row">
      <div class="large-8 columns"><%= yield %></div>
      <div class="large-4 columns">
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id ultricies nisl, ac porta erat. Maecenas eu tristique nulla, at feugiat ipsum. Vivamus dignissim semper tempor. Integer tincidunt est vel metus varius vulputate. Aenean bibendum sollicitudin purus nec semper. Quisque vitae laoreet arcu. Phasellus quis neque sed ante egestas interdum. Fusce lacinia sit amet quam eu lobortis. Curabitur posuere quam euismod tortor aliquam, quis commodo velit dictum.
        </p>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer venenatis ullamcorper elit quis sodales. In lorem odio, placerat sed lectus at, vehicula auctor velit. Aenean erat nunc, rhoncus eu leo vel, auctor fringilla urna. Ut rutrum vitae mi non vestibulum. Sed imperdiet malesuada tortor. Phasellus vel nisi sed arcu scelerisque posuere in vitae est. Vivamus ut nisl tortor. Nulla posuere velit sit amet ullamcorper hendrerit. Vestibulum a magna non lorem convallis tristique.
        </p>
      </div>

    </div>


    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Designwithme" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Designwithme" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= label_tag :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= label_tag :last_name %><br />
      <%= f.text_field :last_name %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit "Save", class: 'button' %></div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Designers</h1>

<%= link_to 'New Designer', new_user_path, class: 'button' %>
<br/>
<br/>

<div class="row">
  <div class="large-8 columns">
    <table width="100%">
      <tr>
        <th>Name</th>
        <th>Email</th>

        <th>Actions</th>
      </tr>

      <% @users.each do |user| %>
          <tr>
            <td><%=link_to user.name, edit_user_path(user) %></td>
            <td><%= user.email %></td>
            <td>
              <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

<br />

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>